name: 'Hello World'
description: 'Greet someone'
inputs: 
  key1:  # id of input
    description: 'key1'
    required: true
    default: 'World' 
outputs: 
  key3:
    description: "Random number"
    value: ${{ steps.key2.outputs.key3 }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.key1 }}. 
      shell: bash
    - id: key2 
      run: echo "::set-output name=key3::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH # O caminho onde uma ação está localizada. Esta propriedade só é compatível com ações compostas. Você pode usar este caminho para acessar arquivos localizados no mesmo repositório da ação.
      shell: bash          
    - run: goodbye.sh
      shell: bash

