name: 'Hello World'
description: 'Greet someone'
inputs: # RECEBE DO WORKFLOW
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World' # o who-to-great usa este dafult caso não seja setado no workflow
outputs: # EXPOE O VALOR PARA O WORKFLOW
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
    #value = step->id: random-number-generator-> outputs -> valor 
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}. # recebe default da action caso não seja setado no workflow
      shell: bash
    - id: random-number-generator # id do outputs e a saida é random-number
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH # PERGUNTAR O MOTIVO ???
      shell: bash          
    - run: goodbye.sh
      shell: bash

